objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory:
    instances:
      description: Certify Management Hub instances inventory source
      name: instances
      version_added: 0.1.0
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 0.1.0
