---
name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  COLLECTION_PATH: ansible_collections/lspiehler/certify_hub

jobs:
  sanity:
    name: Sanity (ansible-core ${{ matrix.ansible }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ansible: stable-2.16
            python: '3.11'
          - ansible: stable-2.17
            python: '3.11'
          - ansible: devel
            python: '3.13'
    steps:
      - name: Checkout collection
        uses: actions/checkout@v5
        with:
          path: ${{ env.COLLECTION_PATH }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install ansible-core (${{ matrix.ansible }})
        run: pip install "https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz"

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color
        working-directory: ${{ env.COLLECTION_PATH }}

  units:
    name: Units (ansible-core ${{ matrix.ansible }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ansible: stable-2.16
            python: '3.11'
          - ansible: stable-2.17
            python: '3.11'
          - ansible: devel
            python: '3.13'
    steps:
      - name: Checkout collection
        uses: actions/checkout@v5
        with:
          path: ${{ env.COLLECTION_PATH }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install ansible-core (${{ matrix.ansible }})
        run: pip install "https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz"

      - name: Run unit tests
        run: ansible-test units --docker -v --color
        working-directory: ${{ env.COLLECTION_PATH }}
